---
- name: Download Sysmon config file
  ansible.builtin.include_tasks:
    file: download_file.yml
  vars:
    ludus_download_file_name: sysmonconfig.xml
    ludus_download_file_url: "{{ ludus_sysmon_config_file_url }}"
    ludus_download_file_host_path: "{{ ludus_sysmon_host_path }}"

- name: Download Sysmon.zip
  ansible.builtin.include_tasks:
    file: download_file.yml
  vars:
    ludus_download_file_name: Sysmon.zip
    ludus_download_file_url: https://download.sysinternals.com/files/Sysmon.zip
    ludus_download_file_host_path: "{{ ludus_sysmon_host_path }}"

- name: Unzip Sysmon.zip
  community.windows.win_unzip:
    src: "{{ ludus_sysmon_zip_host_path }}"
    dest: "{{ ludus_sysmon_host_path }}"

- name: Install Sysmon
  ansible.builtin.win_command:
    argv:
      - "{{ ludus_sysmon_host_path }}\\Sysmon64.exe"
      - -accepteula
      - -i
      - "{{ ludus_sysmon_host_path }}\\sysmonconfig.xml"
